name: Setup Web Remote Desktop with noVNC and Cloudflare Quick Tunnel

on:
  workflow_dispatch:

jobs:
  web-rdp-setup:
    runs-on: windows-latest
    steps:
      - name: Download and Install TightVNC Server
        shell: powershell
        run: |
          # TightVNC最新版ダウンロード (64bit MSI, 2025年8月時点のURL)
          Invoke-WebRequest -Uri "https://www.tightvnc.com/download/2.8.85/tightvnc-2.8.85-gpl-setup-64bit.msi" -OutFile "tightvnc.msi"
          
          # サイレントインストール (/qn for quiet, /norestart)
          msiexec /i tightvnc.msi /qn /norestart ADDLOCAL=Server SET_USEVNCPASSWORD=1 VALUE_OF_USEVNCPASSWORD=YourStrongPassword SET_USECONTROLPASSWORD=1 VALUE_OF_USECONTROLPASSWORD=YourStrongPassword
          
          # VNCサーバー起動
          & "C:\Program Files\TightVNC\tvnserver.exe" -start -silent

      - name: Install noVNC
        shell: powershell
        run: |
          # noVNCリポジトリクローン
          git clone https://github.com/novnc/noVNC.git
          cd noVNC
          
          # noVNCプロキシ起動 (VNCポート5900をWebポート6080に変換)
          # Node.jsが必要ないwebsockify版を使用（noVNCに同梱）
          ./utils/novnc_proxy --vnc localhost:5900 --listen 6080 --web .

      - name: Install cloudflared
        uses: AnimMouse/setup-cloudflared@v1  # Marketplaceアクションで最新版インストール

      - name: Start Cloudflare Quick Tunnel for noVNC
        shell: powershell
        run: |
          # Quick Tunnel起動 (アカウント不要、ランダムURL生成)
          cloudflared tunnel --url http://localhost:6080
          
          # トンネル保持 (ログにURL出力、必要に応じて調整)
          Start-Sleep -Seconds 3600  # 1時間保持、最大6時間
