name: Setup RDP with Cloudflare Quick Tunnel

on: [workflow_dispatch]  # 手動トリガー（Actionsタブから実行）

jobs:
  rdp:
    runs-on: windows-latest
    steps:
      - name: Enable RDP
        shell: powershell
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          net user runneradmin StrongPassword123! /add  # パスワードを強固なものに変更
          net localgroup administrators runneradmin /add

      - name: Setup cloudflared
        uses: AnimMouse/setup-cloudflared@v2

      - name: Setup Cloudflare Quick Tunnel for RDP
        uses: AnimMouse/setup-cloudflared/tunnel@v2
        with:
          url: tcp://localhost:3389  # RDPポートをTCPで公開

      - name: Keep workflow running for connection
        shell: powershell
        run: Start-Sleep -Seconds 30000  # 5分間待機（接続時間を調整）

      - name: Shutdown cloudflared
        if: '!cancelled()'
        uses: AnimMouse/setup-cloudflared/shutdown@v2
