name: RDP with Cloudflare Quick Tunnel

on:
  workflow_dispatch: # 手動実行用

jobs:
  rdp:
    runs-on: windows-latest # Windows Runnerを使用

    steps:
    - name: Set up RDP
      id: rdp_setup
      run: |
        # RDP有効化
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
        # ファイアウォールでRDPポート（3389）を許可
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        
        # 既存のrunneradminユーザーのパスワードを変更
        $username = "runneradmin"
        $password = -join ((48..57) + (65..90) + (97..122) | Get-Random -Count 16 | % {[char]$_})
        $securePassword = ConvertTo-SecureString $password -AsPlainText -Force
        Set-LocalUser -Name $username -Password $securePassword
        
        # GitHub Actionsの出力に設定
        echo "username=$username" >> $env:GITHUB_OUTPUT
        echo "password=$password" >> $env:GITHUB_OUTPUT

    - name: Setup cloudflared
      uses: AnimMouse/setup-cloudflared@v2

    - name: Start Cloudflare Quick Tunnel (RDP)
      id: tunnel
      run: |
        # cloudflaredを実行し、出力をファイルに保存
        $logFile = "$env:TEMP\cloudflared.log"
        $process = Start-Process -FilePath "cloudflared" -ArgumentList "tunnel --url rdp://localhost:3389" -RedirectStandardOutput $logFile -NoNewWindow -PassThru
        
        # URLが出力されるまで待機
        $url = $null
        $timeout = 60 # 60秒待つ（時間を延長）
        $elapsed = 0
        
        Write-Host "Waiting for tunnel URL..."
        
        while ($elapsed -lt $timeout -and -not $url) {
          Start-Sleep -Seconds 2
          $elapsed += 2
          
          if (Test-Path $logFile) {
            $content = Get-Content $logFile -Raw
            
            # URLを抽出する正規表現を改善
            if ($content -match 'https://[a-zA-Z0-9\-]+\.trycloudflare\.com') {
              $url = $matches[0]
              Write-Host "Found tunnel URL: $url"
            }
            
            # デバッグ用にログファイルの内容を表示
            if ($elapsed % 10 -eq 0) {
              Write-Host "Checking log file ($elapsed seconds elapsed):"
              Get-Content $logFile | Select-Object -Last 5
            }
          }
        }
        
        if ($url) {
          echo "tunnel_url=$url" >> $env:GITHUB_OUTPUT
          Write-Host "Cloudflare Tunnel URL: $url"
        } else {
          Write-Host "Failed to get tunnel URL"
          Write-Host "Log file content:"
          if (Test-Path $logFile) {
            Get-Content $logFile
          } else {
            Write-Host "Log file not found"
          }
          exit 1
        }
      shell: pwsh

    - name: Wait for RDP Connection
      run: |
        # 1時間待機（必要に応じて調整）
        Write-Host "Waiting for RDP connections for 1 hour..."
        Start-Sleep -Seconds 3600
      shell: pwsh

    - name: Output RDP Connection Info
      run: |
        echo "==================== RDP Connection Info ===================="
        echo "RDP Username: ${{ steps.rdp_setup.outputs.username }}"
        echo "RDP Password: ${{ steps.rdp_setup.outputs.password }}"
        echo "Cloudflare Tunnel URL: ${{ steps.tunnel.outputs.tunnel_url }}"
        echo "============================================================"
        echo ""
        echo "Connect using the above URL in your RDP client."
        echo "The connection will be available until this workflow times out (1 hour)."
