name: VNC with Latest Cloudflared
on: [workflow_dispatch]
jobs:
  vnc:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y tightvncserver xfce4 xfce4-goodies websockify
        
    - name: Setup VNC
      run: |
        mkdir -p ~/.vnc
        echo "password" | vncpasswd -f > ~/.vnc/passwd
        chmod 600 ~/.vnc/passwd
        cat > ~/.vnc/xstartup << EOF
        #!/bin/bash
        unset SESSION_MANAGER
        unset DBUS_SESSION_BUS_ADDRESS
        exec startxfce4
        EOF
        chmod +x ~/.vnc/xstartup
        vncserver :1 -geometry 1280x720 -depth 24
        
    - name: Download noVNC
      run: |
        git clone https://github.com/novnc/noVNC.git
        cd noVNC
        git checkout v1.4.0
        
    - name: Start websockify
      run: |
        websockify --web=noVNC 6080 localhost:5901 &
        
    - name: Download latest cloudflared
      run: |
        # 最新バージョンを直接ダウンロード
        curl -L https://github.com/cloudflare/cloudflared/releases/download/2024.8.1/cloudflared-linux-amd64.deb -o cloudflared.deb
        sudo dpkg -i cloudflared.deb
        
    - name: Start Cloudflare Tunnel with output capture
      id: tunnel
      run: |
        # 一時ファイルにcloudflaredの出力を保存
        TEMP_FILE=$(mktemp)
        
        # バックグラウンドでcloudflaredを実行
        cloudflared tunnel --url http://localhost:6080 > $TEMP_FILE 2>&1 &
        CLOUDFLARED_PID=$!
        
        # トンネルが起動するのを待つ
        echo "Waiting for tunnel to start..."
        for i in {1..30}; do
          if grep -q "trycloudflare.com" $TEMP_FILE; then
            echo "Tunnel started successfully!"
            break
          fi
          echo "Waiting... ($i/30)"
          sleep 2
        done
        
        # ログを表示
        echo "Tunnel log content:"
        cat $TEMP_FILE
        
        # URLを抽出
        URL=$(grep -o 'https://[-a-zA-Z0-9\.]*\.trycloudflare\.com' $TEMP_FILE | head -1)
        
        # URLが見つからない場合、別の方法で試す
        if [ -z "$URL" ]; then
          echo "Trying alternative method to get URL..."
          URL=$(grep -oE 'https://[a-z0-9\-]+\.trycloudflare\.com' $TEMP_FILE | head -1)
        fi
        
        # 一時ファイルをコピー
        cp $TEMP_FILE tunnel.log
        
        echo "tunnel_url=$URL" >> $GITHUB_OUTPUT
        echo "CLOUDFLARED_PID=$CLOUDFLARED_PID" >> $GITHUB_OUTPUT
        
    - name: Display connection info
      run: |
        echo "================================"
        echo "VNC Connection Information"
        echo "================================"
        echo "URL: ${{ steps.tunnel.outputs.tunnel_url }}"
        echo "Password: password"
        echo "================================"
        echo "Tunnel log content:"
        cat tunnel.log
        echo "================================"
        echo "Waiting for connection..."
        
    - name: Keep alive
      run: |
        sleep 3600
