name: VNC Server with Websockify
on: [workflow_dispatch]
jobs:
  vnc:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y tightvncserver xfce4 xfce4-goodies websockify
        
    - name: Setup VNC
      run: |
        mkdir -p ~/.vnc
        echo "password" | vncpasswd -f > ~/.vnc/passwd
        chmod 600 ~/.vnc/passwd
        cat > ~/.vnc/xstartup << EOF
        #!/bin/bash
        unset SESSION_MANAGER
        unset DBUS_SESSION_BUS_ADDRESS
        exec startxfce4
        EOF
        chmod +x ~/.vnc/xstartup
        vncserver :1 -geometry 1280x720 -depth 24
        
    - name: Download noVNC
      run: |
        git clone https://github.com/novnc/noVNC.git
        cd noVNC
        git checkout v1.4.0
        
    - name: Start websockify manually
      run: |
        websockify --web=noVNC 6080 localhost:5901 &
        
    - name: Install bore
      run: |
        curl -L https://github.com/ekzhang/bore/releases/download/v0.4.0/bore-v0.4.0-x86_64-unknown-linux-musl.tar.gz | tar xz
        sudo mv bore /usr/local/bin/
        
    - name: Start tunnel
      run: |
        bore local 6080 --to bore.pub &
        echo "Access noVNC at: https://bore.pub:2662/vnc.html"
        
    - name: Keep alive
      run: |
        sleep 3600
