name: Setup RDP with Cloudflare Quick Tunnel

on:
  workflow_dispatch:

jobs:
  rdp-setup:
    runs-on: windows-latest
    steps:
      - name: Enable RDP and Set Password
        shell: powershell
        run: |
          # RDPを有効化
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          
          # ユーザー有効化とパスワード設定（任意のパスワードに変更）
          net user runneradmin /active:yes
          net user runneradmin P@ssw0rd123!  # ここを強力なパスワードに変更
          
          # RDPが有効か確認
          Get-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections"

      - name: Install cloudflared
        uses: AnimMouse/setup-cloudflared@v1  # GitHub Marketplaceのアクションでインストール（最新版自動取得）

      - name: Start Cloudflare Quick Tunnel for RDP
        shell: powershell
        run: |
          # Quick Tunnelを起動（アカウント不要、ランダムURL生成）
          cloudflared tunnel --url rdp://localhost:3389
          
          # トンネルが起動するまで待機（URLはログに出力される）
          Start-Sleep -Seconds 3600  # ジョブを1時間保持（必要に応じて調整、最大6時間）
